#cloud-config
users:
  - default
  - name: iacadmin
    groups: [adm, sudo]
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    lock_passwd: true
ssh_pwauth: false
runcmd:
  - [ sh, -c, "systemctl enable --now open-vm-tools || true" ]
final_message: "IaC Ubuntu template clone is ready."
