[defaults]
ssh_public_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIA+W2ocEhkGCkUoOyethivfABUp4Cl76oyA5SW0li21 iac-template@sysap"
username = "iacadmin"
groups = ["adm", "sudo"]
shell = "/bin/bash"
sudo = "ALL=(ALL) NOPASSWD:ALL"
gateway = "10.1.0.254"
prefix = 24
dns_servers = ["10.1.0.9", "10.1.0.254"]
interface_match = "en*"
template = "tpl-ubuntu-24.04-server"
cpu = 2
memory_mb = 4096
disk_gb = 40
runcmd = [
  "systemctl enable --now open-vm-tools || true",
]

[[vm]]
name = "iac-linux-managed-10-01"
ipv4 = "10.1.0.131"
instance_id = "iac-linux-managed-10-01-nocloud"
datacenter = "Datacenter SVB"
cluster = "SVB Cluster"
datastore = "MSA2060-Datastore2"
network = "SVB Server"
seed_iso_path = "iac/seed/iac-linux-managed-10-01-seed.iso"

[[vm]]
name = "iac-linux-managed-10-02"
ipv4 = "10.1.0.132"
instance_id = "iac-linux-managed-10-02-nocloud"
datacenter = "Datacenter SVB"
cluster = "SVB Cluster"
datastore = "MSA2060-Datastore2"
network = "SVB Server"
seed_iso_path = "iac/seed/iac-linux-managed-10-02-seed.iso"

[[vm]]
name = "iac-linux-managed-10-03"
ipv4 = "10.1.0.133"
instance_id = "iac-linux-managed-10-03-nocloud"
datacenter = "Datacenter SVB"
cluster = "GZ Cluster"
datastore = "Web-Datastore"
network = "SVB Server"
seed_iso_path = "iac/seed/iac-linux-managed-10-03-seed.iso"

[[vm]]
name = "iac-linux-managed-10-04"
ipv4 = "10.1.0.134"
instance_id = "iac-linux-managed-10-04-nocloud"
datacenter = "Datacenter SVB"
cluster = "GZ Cluster"
datastore = "Web-Datastore"
network = "SVB Server"
seed_iso_path = "iac/seed/iac-linux-managed-10-04-seed.iso"
